import { clamp, clamp01, smoothstep } from '../core/MathUtils';
import type { CompoundId, TireCompound } from '../data/tires';
import { getCompound } from '../data/tires';

/**
 * Per-axle tire state: temperature, wear, and the grip that falls out of them.
 *
 * Three separate effects reduce grip, and keeping them separate is what makes
 * strategy interesting rather than a single "tire life" bar:
 *
 *  1. TEMPERATURE. Grip peaks inside a window and falls away on both sides.
 *     Below the window the tire is cold and greasy; above it, it is greasy for a
 *     different reason. Temperature responds within a corner or two, so it is
 *     the effect the driver feels immediately.
 *
 *  2. WEAR. Monotonic and irreversible. Degrades slowly at first, then falls off
 *     a cliff — the "cliff" is real and is what forces a pit stop.
 *
 *  3. SURFACE CONDITION. Flat spots from lock-ups and graining from sliding.
 *     Recoverable in part, unlike wear.
 *
 * Heat is generated by slip *power* (slip velocity times load), which is the
 * physically right driver: sliding a loaded tire is what heats it. That means
 * following another car closely, sliding through a long corner, or over-driving
 * into a hairpin all heat the tires without any special-case code.
 */

/** Wear level below which grip starts falling off sharply. */
const CLIFF_START = 0.4;

export class TireState {
  compound: TireCompound;

  /** 1.0 = new, 0.0 = destroyed. */
  wear = 1;
  /** Bulk carcass temperature, °C. */
  tempC = 80;
  /** Surface condition, 1.0 = clean. Lock-ups and graining reduce it. */
  surface = 1;
  /** Laps completed on this set, used for warm-up. */
  lapsOnSet = 0;
  /** Distance covered on this set, metres. */
  distanceOnSet = 0;

  /** Instantaneous slip ratio magnitude, for telemetry and lock-up detection. */
  slipRatio = 0;
  /** Instantaneous slip angle magnitude, radians. */
  slipAngle = 0;

  /** Cached grip multiplier, recomputed each physics step. */
  grip = 1;

  constructor(compound: CompoundId = 'medium', startTempC = 80) {
    this.compound = getCompound(compound);
    this.tempC = startTempC;
  }

  /** Fits a fresh set. Called on a pit stop and at session start. */
  fit(compound: CompoundId, blanketTempC: number): void {
    this.compound = getCompound(compound);
    this.wear = 1;
    this.surface = 1;
    this.lapsOnSet = 0;
    this.distanceOnSet = 0;
    this.tempC = blanketTempC;
    this.slipRatio = 0;
    this.slipAngle = 0;
    this.grip = 1;
  }

  /**
   * Advances temperature, wear and surface condition, then recomputes grip.
   *
   * @param dt            physics timestep, seconds
   * @param slipSpeedMs   magnitude of the contact patch's sliding velocity
   * @param loadN         vertical load on this axle
   * @param staticLoadN   load with no downforce, for normalising wear
   * @param trackTempC    surface temperature the tire exchanges heat with
   * @param wetness       0 dry .. 1 standing water
   * @param abrasion      circuit surface abrasion multiplier
   */
  update(
    dt: number,
    slipSpeedMs: number,
    loadN: number,
    staticLoadN: number,
    trackTempC: number,
    wetness: number,
    abrasion: number,
  ): void {
    const c = this.compound;

    // --- Temperature -------------------------------------------------------
    // Heat in is slip power: sliding velocity times load. Divided through by
    // static load so the coefficient is dimensionally stable across cars.
    const loadRatio = loadN / Math.max(staticLoadN, 1);
    const slipPower = slipSpeedMs * loadRatio;
    const heatIn = slipPower * c.heatingRate * 0.78;

    // Heat out is convection toward the track, plus airflow that scales with
    // speed. Water on the track is an aggressive heat sink — which is exactly
    // why slicks never come up to temperature in the rain.
    const ambientTarget = trackTempC + 18 - wetness * 30;
    const airflow = 1 + slipSpeedMs * 0.02;
    const heatOut = (this.tempC - ambientTarget) * c.coolingRate * 0.085 * airflow;

    this.tempC += (heatIn - heatOut) * dt;
    this.tempC = clamp(this.tempC, 5, 260);

    // --- Wear --------------------------------------------------------------
    // Wear is driven by slip, load and temperature. Running the tire hot wears
    // it far faster than running it in the window, so overheating costs twice:
    // grip now, and life later.
    const overheat = Math.max(0, this.tempC - c.optimalTempMaxC);
    const thermalWearMult = 1 + overheat * overheat * 0.0016;
    const wearPerSecond =
      slipPower * c.wearRate * abrasion * thermalWearMult * 7.4e-6;
    this.wear = Math.max(0, this.wear - wearPerSecond * dt);

    // --- Surface condition -------------------------------------------------
    // A big slip event grains or flat-spots the surface. It partially recovers
    // once the driver stops abusing it.
    if (slipSpeedMs > 6) {
      this.surface = Math.max(0.55, this.surface - (slipSpeedMs - 6) * 0.0016 * dt);
    } else {
      this.surface = Math.min(1, this.surface + 0.035 * dt);
    }

    this.distanceOnSet += slipSpeedMs * dt;
    this.grip = this.computeGrip(wetness);
  }

  /**
   * Grip multiplier from all effects combined.
   * This is the single number the vehicle physics multiplies its friction by.
   */
  computeGrip(wetness: number): number {
    const c = this.compound;
    return (
      c.peakGrip *
      this.thermalFactor() *
      this.wearFactor() *
      this.surface *
      this.wetFactor(wetness) *
      this.warmupFactor()
    );
  }

  /**
   * Grip vs temperature: flat inside the window, falling away outside it.
   *
   * Below the window the fall is gentler than above — a cold tire is slow but a
   * cooked tire is genuinely dangerous, and that asymmetry is what makes
   * overheating the thing to manage.
   */
  thermalFactor(): number {
    const c = this.compound;
    const t = this.tempC;
    if (t >= c.optimalTempMinC && t <= c.optimalTempMaxC) return 1;

    if (t < c.optimalTempMinC) {
      const deficit = c.optimalTempMinC - t;
      // 30 degrees cold costs roughly 12% grip.
      const f = 1 - (deficit / 30) * 0.12 * c.thermalSensitivity;
      return clamp(f, 0.55, 1);
    }

    const excess = t - c.optimalTempMaxC;
    // Quadratic above the window: 20 degrees hot is survivable, 60 is not.
    const f = 1 - (excess * excess) / 5200 * c.thermalSensitivity;
    return clamp(f, 0.42, 1);
  }

  /**
   * Grip vs wear. Nearly flat down to 40% life, then an exponential cliff.
   *
   * The cliff is the whole point: it means a stint has a natural end rather than
   * a linear decline the player can ignore, and it is why teams pit before the
   * tire is "gone" rather than after.
   */
  wearFactor(): number {
    const w = this.wear;
    if (w >= CLIFF_START) {
      // Gentle linear loss across the healthy range: ~6% by the cliff.
      return 1 - (1 - w) * 0.1;
    }
    // Below the cliff, grip decays exponentially in how far past it we are.
    const past = (CLIFF_START - w) / CLIFF_START; // 0 at cliff, 1 at destroyed
    const atCliff = 1 - (1 - CLIFF_START) * 0.1;
    return atCliff * Math.exp(-2.35 * past * past);
  }

  /** Grip vs standing water, interpolated through the compound's wet curve. */
  wetFactor(wetness: number): number {
    // Indexed rather than destructured: array destructuring allocates an
    // iterator, and this runs twice per car per physics step.
    const curve = this.compound.wetGripCurve;
    const w = clamp01(wetness);
    return w < 0.5
      ? curve[0] + (curve[1] - curve[0]) * (w * 2)
      : curve[1] + (curve[2] - curve[1]) * ((w - 0.5) * 2);
  }

  /** Grip ramp over the first lap or so on a new set. */
  warmupFactor(): number {
    const need = this.compound.warmupLaps;
    if (need <= 0) return 1;
    return 0.9 + 0.1 * smoothstep(0, need, this.lapsOnSet);
  }

  /** Called by the session when the car crosses the line. */
  onLapComplete(): void {
    this.lapsOnSet++;
  }

  /**
   * Applies flat-spotting while a wheel is locked.
   *
   * `excess` is how far the brake demand exceeded the grip budget (0.2 = 20%
   * over) and `dt` the timestep, so the damage rate is per-second rather than
   * per-call. Getting that wrong creates a runaway: damage lowers grip, lower
   * grip raises the excess, which damages faster. A second of fully locked
   * wheels should cost a noticeable chunk of grip, not all of it.
   *
   * The floor matters too. A flat-spotted tire vibrates and loses maybe a third
   * of its grip; it does not become ice. Letting it approach zero turned a
   * lock-up into an unrecoverable death spiral.
   */
  flatSpot(excess: number, dt: number): void {
    const rate = clamp(excess, 0, 1.5);
    this.surface = Math.max(0.68, this.surface - rate * 0.09 * dt);
    this.wear = Math.max(0, this.wear - rate * 0.004 * dt);
    this.tempC += rate * 30 * dt;
  }

  /** Estimated laps remaining before the cliff, for the strategy UI. */
  estimatedLapsToCliff(wearPerLap: number): number {
    if (wearPerLap <= 1e-6) return 99;
    return Math.max(0, (this.wear - CLIFF_START) / wearPerLap);
  }

  /** 0..1 for the HUD bar. */
  get lifePercent(): number {
    return this.wear;
  }

  /** Temperature relative to the window: -1 cold, 0 ideal, +1 hot. */
  get thermalBalance(): number {
    const c = this.compound;
    const mid = (c.optimalTempMinC + c.optimalTempMaxC) * 0.5;
    const half = (c.optimalTempMaxC - c.optimalTempMinC) * 0.5;
    return clamp((this.tempC - mid) / Math.max(half, 1), -3, 3);
  }
}
