import * as THREE from 'three';
import { RGBELoader } from 'three/examples/jsm/loaders/RGBELoader.js';

/**
 * The environment probe: the thing the car's paint reflects.
 *
 * SINCE ISSUE #78 THERE ARE TWO OF THEM, AND THE PROCEDURAL ONE IS THE FALLBACK.
 *
 * Everything below the divider is the generated probe, unchanged, and it is
 * still what the first frame of every session is lit by. What sits on top of it
 * now is a real captured sky — a CC0 Poly Haven HDRI from `public/assets/hdri/`
 * — loaded asynchronously and swapped in when it arrives.
 *
 * The reason to do it in that order rather than simply replacing the generated
 * probe is the same reason `public/brand/` was specified as an asset SLOT in
 * PROJECT.md §3: `public/assets/` is gitignored and regenerated by
 * `scripts/fetchAssets.ts`, so a clone that has never run the fetcher, a build
 * with the directory deleted, and a player on a connection that drops the
 * request must all still get a lit scene. They do: `apply()` installs the
 * generated probe synchronously every time, and the HDRI only ever *replaces*
 * an image that was already correct. Deleting `public/assets/hdri/` returns the
 * renderer to exactly its pre-#78 behaviour, which is the guarantee that makes
 * the asset optional rather than required.
 *
 * WHAT THE CAPTURED SKY BUYS, IN ONE SENTENCE: the generated probe is a 256x128
 * analytic function — a gradient, a haze band, three sine terms and a sun disc —
 * and a `MeshStandardMaterial` integrating that over a roughness cone gets back
 * something very close to a constant. A 2048x1024 photograph of a real sky has
 * structure at every scale, so the same integral returns a different number for
 * every surface normal, and *that* is what makes clear coat and metal read as
 * clear coat and metal rather than as tinted plastic.
 *
 * THE SUN IN THE PROBE DID NOT AGREE WITH THE SUN IN THE SCENE, and this is
 * where that is fixed. `Renderer.applyAmbience` already takes care to point the
 * sky dome's disc at the key light — "so the halo, the silver lining on the
 * cloud edges and the shadows on the track all agree" — and then hands the probe
 * nothing at all. `PALETTES.day.sunAzimuth` is 205 degrees, i.e. atan2(x,z) of
 * (-0.42, ., -0.91); the day key light stands at (-220, 400, 180), which is
 * 309.3 degrees. **The reflected highlight came from 104 degrees away from the
 * light casting the shadow**, and has since the probe was written. The
 * generated probe is left as it is, because moving its sun would move every
 * highlight in every audit shot on `main` for no measured reason; the loaded
 * HDRI is scanned for its OWN brightest direction and rotated so that direction
 * lands on the key light's azimuth. Rotating the environment rather than moving
 * the light is deliberate: the shadow direction is what `probe:framing`,
 * `probe:banking` and every audit shot in the repository are laid out against,
 * and none of them should move for a reflection fix.
 *
 * This is the highest-leverage object in the whole renderer, and the reason is
 * worth stating plainly, because the first version of it got this exactly wrong.
 *
 * A `MeshStandardMaterial` computes its specular response by integrating the
 * environment over a cone whose width is set by roughness. If the environment is
 * a SMOOTH GRADIENT, that integral is — to within a few percent — the same
 * number everywhere on a curved panel. Which means the reflection term is a flat
 * wash, the diffuse term is a flat wash, and the sum of two flat washes is
 * painted plastic. That is what the previous 64x64 "bright above, dark below,
 * warm on one side" probe produced, and no amount of tuning roughness rescues
 * it, because the information simply is not in the probe.
 *
 * What makes a car look like a car is CONTRAST IN THE PROBE, specifically:
 *
 *  - A HARD HORIZON. The single most important feature. Sky is bright, ground is
 *    dark, and the line between them is sharp. As a curved flank turns past the
 *    horizon, its reflection sweeps from bright to dark across a few centimetres
 *    — that travelling light/dark boundary along a sidepod is the whole reason
 *    the shape reads as a shape. A probe without a horizon has no shape cue at
 *    all.
 *  - A SMALL, VERY BRIGHT SUN. Order 100x the sky's radiance, not 1.2x. This is
 *    what puts a compact hot highlight on the airbox and along the halo, and it
 *    only works if the probe is float — an 8-bit probe clips it to the same
 *    white as the sky and the highlight disappears into the wash.
 *  - HORIZONTAL STRUCTURE. Cloud banding by day, a ring of floodlights at night,
 *    a bright horizon haze band always. These stretch into the long streaky
 *    highlights that run the length of a real car's bodywork. They are the
 *    difference between "shiny" and "wet-looking".
 *
 * Cost: one 256x128 float image, generated once per ambience, PMREM-filtered,
 * and then it is free forever. There are no image files in this project and
 * there will not be any.
 */

export type Ambience = 'day' | 'dusk' | 'night';

/** Equirectangular probe resolution. PMREM downsamples anyway; this is plenty. */
const W = 256;
const H = 128;

interface Palette {
  /** Zenith, horizon-sky, and ground colours as linear RGB triples. */
  zenith: [number, number, number];
  horizon: [number, number, number];
  ground: [number, number, number];
  /** Sun colour and peak radiance multiplier. */
  sun: [number, number, number];
  sunPower: number;
  /** Elevation of the sun, in degrees above the horizon. */
  sunElevation: number;
  /** Azimuth of the sun, in degrees. */
  sunAzimuth: number;
  /** Strength of the bright haze band sitting on the horizon. */
  hazeBoost: number;
  /** Cloud/floodlight banding strength. */
  banding: number;
  /** Number of discrete light sources around the horizon (floodlights). */
  floodlights: number;
  /** Radiance of each floodlight. */
  floodPower: number;
  /** Colour of the floodlights. */
  floodColour: [number, number, number];
}

const PALETTES: Record<Ambience, Palette> = {
  day: {
    zenith: [0.06, 0.13, 0.34],
    horizon: [0.55, 0.66, 0.82],
    ground: [0.035, 0.036, 0.040],
    sun: [1.0, 0.93, 0.80],
    sunPower: 220,
    sunElevation: 52,
    sunAzimuth: 205,
    hazeBoost: 1.5,
    // Enough to draw a moving highlight down a flank, not enough to read as
    // wood grain. Above about 0.3 the bands stop looking like reflected cloud
    // and start looking like a texture painted on the paint.
    banding: 0.26,
    floodlights: 0,
    floodPower: 0,
    floodColour: [1, 1, 1],
  },
  dusk: {
    zenith: [0.035, 0.055, 0.16],
    horizon: [0.85, 0.36, 0.20],
    ground: [0.022, 0.018, 0.020],
    sun: [1.0, 0.55, 0.22],
    sunPower: 90,
    sunElevation: 6,
    sunAzimuth: 250,
    hazeBoost: 2.1,
    banding: 0.55,
    floodlights: 0,
    floodPower: 0,
    floodColour: [1, 1, 1],
  },
  night: {
    // A night probe is NOT "the day probe, darker". At night the only things
    // that reflect are the floodlights, and they are point-like and violently
    // brighter than everything else in frame. That ratio — a near-black dome
    // punctured by a ring of small hot sources — is exactly what produces the
    // hard specular streaks running along a car's flanks under lights, and it
    // is the entire reason the reference footage reads as a night race rather
    // than as a grey race.
    // The sky is genuinely near-black, but the band around the horizon is not:
    // it is full of lit grandstand, lit run-off and the city glow behind, and
    // that band is where a car on a flat piece of road takes most of its
    // reflection from.
    zenith: [0.004, 0.006, 0.016],
    horizon: [0.070, 0.076, 0.098],
    ground: [0.030, 0.030, 0.033],
    sun: [0.5, 0.6, 0.9],
    sunPower: 0,
    sunElevation: 60,
    sunAzimuth: 30,
    hazeBoost: 1.9,
    banding: 0.20,
    floodlights: 14,
    // Hot enough that a gloss panel returns a clipped white streak, which is
    // what a floodlit car actually does, but not so hot that the streak spreads
    // across the whole flank and erases the livery under it.
    floodPower: 20,
    floodColour: [1.0, 0.97, 0.88],
  },
};

/** Smooth Hermite step, matching the GLSL builtin. */
function smoothstep(a: number, b: number, x: number): number {
  const t = Math.min(1, Math.max(0, (x - a) / (b - a)));
  return t * t * (3 - 2 * t);
}

/**
 * Renders the probe into a half-float equirectangular texture.
 *
 * Float matters more here than resolution. The sun is two hundred times the
 * radiance of the sky; in eight bits both are 255 and the car loses its
 * highlight entirely.
 */
function renderProbe(p: Palette, wetness: number): THREE.DataTexture {
  const data = new Float32Array(W * H * 4);

  const sunEl = (p.sunElevation * Math.PI) / 180;
  const sunAz = (p.sunAzimuth * Math.PI) / 180;
  const sunDir: [number, number, number] = [
    Math.cos(sunEl) * Math.sin(sunAz),
    Math.sin(sunEl),
    Math.cos(sunEl) * Math.cos(sunAz),
  ];

  // Overcast flattens the probe: a wet race genuinely has no hard sun, and
  // leaving one in is why an overcast scene can still show a hot highlight
  // that agrees with nothing else on screen.
  const sunPower = p.sunPower * (1 - wetness * 0.85);
  const bandAmount = p.banding * (1 - wetness * 0.5);

  for (let y = 0; y < H; y++) {
    // v = 0 at the top of the sphere.
    const theta = ((y + 0.5) / H) * Math.PI;
    const cy = Math.cos(theta);
    const sy = Math.sin(theta);

    for (let x = 0; x < W; x++) {
      const phi = ((x + 0.5) / W) * Math.PI * 2;
      const dx = sy * Math.sin(phi);
      const dz = sy * Math.cos(phi);
      const dy = cy;

      let r: number, g: number, b: number;

      if (dy >= 0) {
        // --- Sky ---------------------------------------------------------
        // Biased toward the horizon so most of the dome's dynamic range sits
        // in the band a car actually reflects.
        const t = Math.pow(dy, 0.42);
        r = p.horizon[0] + (p.zenith[0] - p.horizon[0]) * t;
        g = p.horizon[1] + (p.zenith[1] - p.horizon[1]) * t;
        b = p.horizon[2] + (p.zenith[2] - p.horizon[2]) * t;

        // Horizontal banding. Low-frequency in elevation, so it stretches into
        // long highlights along a flank rather than dappling it.
        const band =
          Math.sin(dy * 11.0 + phi * 1.7) * 0.5 +
          Math.sin(dy * 23.0 - phi * 2.9) * 0.3 +
          Math.sin(dy * 41.0 + phi * 0.8) * 0.2;
        const bandMask = smoothstep(0.02, 0.55, dy) * (1 - smoothstep(0.6, 1.0, dy));
        const k = 1 + band * bandAmount * bandMask;
        r *= k; g *= k; b *= k;
      } else {
        // --- Ground ------------------------------------------------------
        // Dark, and slightly warmer looking straight down. The important part
        // is not what colour it is, it is that it is DARK and that the edge
        // against the sky is sharp.
        const t = Math.pow(-dy, 0.6);
        const fade = 1 - t * 0.45;
        r = p.ground[0] * fade;
        g = p.ground[1] * fade;
        b = p.ground[2] * fade;

        // Wet asphalt mirrors the sky back up. This is what makes a car look
        // like it is standing on a wet track rather than floating over a hole.
        if (wetness > 0.02) {
          const m = wetness * 0.55 * (1 - smoothstep(0.0, 0.5, -dy));
          r += p.horizon[0] * m;
          g += p.horizon[1] * m;
          b += p.horizon[2] * m;
        }
      }

      // --- Horizon haze band -----------------------------------------------
      // A bright, narrow strip sitting exactly on the horizon. This is the
      // brightest large feature in most real environments — distant sky through
      // haze, or the lit run-off and pit buildings — and it is what draws the
      // long horizontal highlight down the length of a sidepod.
      const haze = Math.exp(-Math.abs(dy) * 26.0) * p.hazeBoost;
      r += p.horizon[0] * haze;
      g += p.horizon[1] * haze;
      b += p.horizon[2] * haze;

      // --- Sun -------------------------------------------------------------
      if (sunPower > 0) {
        const d = dx * sunDir[0] + dy * sunDir[1] + dz * sunDir[2];
        if (d > 0) {
          // A small hard disc plus a wide forward-scattering skirt. The skirt
          // is what stops the highlight looking like a sticker.
          const disc = smoothstep(0.9975, 0.9995, d) * sunPower;
          const skirt = Math.pow(d, 220) * sunPower * 0.22 + Math.pow(d, 9) * 0.25;
          const s = disc + skirt;
          r += p.sun[0] * s;
          g += p.sun[1] * s;
          b += p.sun[2] * s;
        }
      }

      // --- Floodlights -------------------------------------------------------
      // A ring of small, very hot sources at about 18 degrees of elevation,
      // which is roughly where a real circuit's masts sit relative to a car.
      if (p.floodlights > 0) {
        const el = Math.asin(Math.max(-1, Math.min(1, dy)));
        for (let i = 0; i < p.floodlights; i++) {
          const a = (i / p.floodlights) * Math.PI * 2;
          // Two rows, slightly staggered, so a rotating car sweeps through them
          // continuously instead of strobing.
          const targetEl = (i % 2 === 0 ? 17 : 25) * (Math.PI / 180);
          let da = phi - a;
          while (da > Math.PI) da -= Math.PI * 2;
          while (da < -Math.PI) da += Math.PI * 2;
          const de = el - targetEl;
          const d2 = (da * da) / 0.0016 + (de * de) / 0.0009;
          if (d2 < 24) {
            const s = Math.exp(-d2) * p.floodPower;
            r += p.floodColour[0] * s;
            g += p.floodColour[1] * s;
            b += p.floodColour[2] * s;
          }
        }
      }

      const o = (y * W + x) * 4;
      data[o] = r;
      data[o + 1] = g;
      data[o + 2] = b;
      data[o + 3] = 1;
    }
  }

  const tex = new THREE.DataTexture(data, W, H, THREE.RGBAFormat, THREE.FloatType);
  tex.mapping = THREE.EquirectangularReflectionMapping;
  // Already linear radiance: no colour-space conversion wanted.
  tex.colorSpace = THREE.NoColorSpace;
  tex.magFilter = THREE.LinearFilter;
  tex.minFilter = THREE.LinearFilter;
  tex.needsUpdate = true;
  return tex;
}

// ---------------------------------------------------------------------------
// The captured sky.
// ---------------------------------------------------------------------------

/**
 * Which CC0 Poly Haven capture each ambience reflects, dry and wet.
 *
 * The wet column is not decoration. `renderProbe` already flattens the
 * generated sun by `1 - wetness * 0.85` for a stated reason — a wet race has no
 * hard sun, and leaving one in puts a hot highlight on the car that agrees with
 * nothing else on screen. A photographed sky cannot be flattened that way
 * without destroying the structure it was loaded for, so the wet case swaps to
 * a genuinely overcast capture instead, which is the same correction made with
 * the right instrument.
 *
 * Night has no wet variant because there is no CC0 overcast-night capture in
 * the fetched set, and substituting the dry one is the honest answer rather
 * than dimming a clear sky and calling it cloud.
 */
const HDRI_FOR: Record<Ambience, { dry: string; wet: string } | null> = {
  day: { dry: 'partly_cloudy', wet: 'overcast' },
  dusk: { dry: 'sunset', wet: 'overcast' },
  /**
   * NIGHT KEEPS THE GENERATED PROBE, AND THIS IS A MEASUREMENT, NOT AN
   * OVERSIGHT.
   *
   * `hdri/night` is Poly Haven's Dikhololo Night: a genuinely beautiful RURAL
   * sky, which is to say a starfield over dark veld with no artificial light in
   * it anywhere. A Formula 1 circuit at night is the exact opposite — it is one
   * of the most intensely lit outdoor spaces there is — and the thing a car's
   * paint reflects there is not sky at all, it is two hundred metal-halide
   * lamps. The generated night probe models precisely that: `PALETTES.night`
   * carries fourteen point sources at 20x radiance in two staggered rows, and
   * its own comment explains that the ratio between a near-black dome and a
   * ring of small hot sources is what produces the hard specular streaks along
   * a floodlit car's flanks.
   *
   * Swapping that for a rural capture was tried and it is a straight
   * downgrade: it removes the only bright features in the probe and leaves the
   * cars matte. So day and dusk take the photograph, because a real sky beats
   * three sine terms, and night keeps the analytic probe, because a real sky of
   * the WRONG PLACE loses to a deliberate model of the right one. There is no
   * CC0 capture of a floodlit stadium in the fetched set; if one is ever added
   * this is the one line that changes.
   */
  night: null,
};

/**
 * Scene environment intensity per ambience.
 *
 * A captured sky carries absolute radiance and a generated one carries whatever
 * the palette's author typed, so the two do not arrive at the same exposure and
 * pretending they do is how an HDRI lands looking either washed out or black.
 * These are set from measurement — `npm run probe:grade`, the frame's median
 * luma and RMS contrast against the reference frame for the same conditions —
 * and not from looking at it. See PROJECT.md section 6 for the numbers.
 */
const HDRI_INTENSITY: Record<Ambience, number> = {
  day: 1.0,
  dusk: 1.0,
  night: 1.0,
};

interface LoadedHdri {
  target: THREE.WebGLRenderTarget;
  /** Azimuth of the capture's own brightest direction, radians, or null. */
  sunAzimuth: number | null;
}

/**
 * Luminance-weighted centroid of the brightest part of an equirectangular sky.
 *
 * Not "the single brightest texel": on a 2K capture that is one pixel of sun
 * core and its position is set as much by sensor noise as by where the sun is.
 * This takes every texel above the horizon carrying more than a fixed fraction
 * of the peak and averages their DIRECTIONS by radiance, which lands on the
 * centre of the solar disc and is stable against a hot cloud edge.
 *
 * Returns null when nothing in the sky is more than a few times the mean —
 * i.e. an overcast or night capture with no sun in it — because rotating an
 * evenly lit dome to align a sun it does not have would be superstition.
 */
function brightestAzimuth(tex: THREE.DataTexture): number | null {
  const img = tex.image as { data: ArrayLike<number>; width: number; height: number };
  const data = img.data;
  const w = img.width;
  const h = img.height;
  if (!data || !w || !h) return null;

  // Peak and mean over the upper hemisphere only.
  let peak = 0;
  let sum = 0;
  let count = 0;
  for (let y = 0; y < h / 2; y++) {
    for (let x = 0; x < w; x++) {
      const o = (y * w + x) * 4;
      const l = 0.2126 * data[o] + 0.7152 * data[o + 1] + 0.0722 * data[o + 2];
      if (l > peak) peak = l;
      sum += l;
      count++;
    }
  }
  const mean = count ? sum / count : 0;
  // A clear sky's sun is orders of magnitude over the mean; an overcast one is
  // under 10x. Below that there is no sun to align.
  if (mean <= 0 || peak / mean < 25) return null;

  const cut = peak * 0.5;
  let vx = 0;
  let vz = 0;
  let wsum = 0;
  for (let y = 0; y < h / 2; y++) {
    const theta = ((y + 0.5) / h) * Math.PI;
    const sy = Math.sin(theta);
    for (let x = 0; x < w; x++) {
      const o = (y * w + x) * 4;
      const l = 0.2126 * data[o] + 0.7152 * data[o + 1] + 0.0722 * data[o + 2];
      if (l < cut) continue;
      // Equirectangular convention matching three's own mapping.
      const phi = ((x + 0.5) / w) * Math.PI * 2;
      vx += Math.sin(phi) * sy * l;
      vz += Math.cos(phi) * sy * l;
      wsum += l;
    }
  }
  if (wsum <= 0) return null;
  return Math.atan2(vx / wsum, vz / wsum);
}

/**
 * Owns the scene's environment map and swaps it when the ambience changes.
 *
 * Holds one generated PMREM target at a time and disposes the previous one,
 * because a session change that leaked a PMREM target per load would quietly
 * eat a few megabytes of VRAM per circuit visited. Loaded HDRIs are cached by
 * name for the lifetime of the renderer instead — there are four of them, they
 * are expensive to filter, and a player moving between sessions revisits the
 * same two.
 */
export class EnvProbe {
  /**
   * False until a captured sky is actually installed. Read by the probe, so
   * that a run which silently fell back cannot be reported as a run that did
   * not — PROJECT.md section 3.2.
   */
  hdriActive = false;
  /** The capture currently installed, for the probe's report. */
  hdriName = '';

  private pmrem: THREE.PMREMGenerator;
  private target: THREE.WebGLRenderTarget | null = null;
  private key = '';
  private readonly hdri = new Map<string, Promise<LoadedHdri | null>>();
  /** The key `apply` was last called with. Guards a late load arriving stale. */
  private wanted = '';

  constructor(renderer: THREE.WebGLRenderer) {
    this.pmrem = new THREE.PMREMGenerator(renderer);
    this.pmrem.compileEquirectangularShader();
  }

  /**
   * Builds the probe for an ambience and applies it to the scene.
   * A repeat call with the same parameters is free.
   *
   * Returns synchronously with the generated probe installed, every time. If a
   * capture for these conditions is on disk it replaces it a few hundred
   * milliseconds later; if it is not, nothing further happens and the scene is
   * lit exactly as it was before issue #78.
   */
  apply(
    scene: THREE.Scene,
    ambience: Ambience,
    wetness: number,
    /**
     * Where the scene's key light stands, in world space. The capture is
     * rotated so its own sun lands here. Omitting it leaves the capture at the
     * orientation it was shot at, which is what the generated probe effectively
     * did and which is the bug described at the top of this file.
     */
    sunPosition?: THREE.Vector3,
  ): void {
    // Quantised, so drizzle drifting from 0.30 to 0.31 does not rebuild and
    // re-filter the probe every frame.
    const w = Math.round(Math.min(1, Math.max(0, wetness)) * 4) / 4;
    const key = `${ambience}:${w}`;
    this.wanted = key;

    if (key !== this.key || !this.target) {
      const src = renderProbe(PALETTES[ambience], w);
      const next = this.pmrem.fromEquirectangular(src);
      src.dispose();
      this.target?.dispose();
      this.target = next;
      this.key = key;
    }

    // The generated probe goes on FIRST and unconditionally. Everything after
    // this point is an upgrade to an image that is already correct.
    scene.environment = this.target!.texture;
    scene.environmentIntensity = 1;
    scene.environmentRotation.set(0, 0, 0);
    this.hdriActive = false;
    this.hdriName = '';

    const wantAzimuth = sunPosition
      ? Math.atan2(sunPosition.x, sunPosition.z)
      : null;

    const set = HDRI_FOR[ambience];
    if (!set) return; // night: the generated probe IS the right answer. See above.
    const name = w >= 0.35 ? set.wet : set.dry;
    void this.load(name).then((loaded) => {
      // A session may have changed circuit, or the weather may have moved,
      // while a 5MB Radiance file was in flight.
      if (!loaded || this.wanted !== key) return;
      scene.environment = loaded.target.texture;
      scene.environmentIntensity = HDRI_INTENSITY[ambience];
      scene.environmentRotation.set(
        0,
        loaded.sunAzimuth === null || wantAzimuth === null
          ? 0
          : wantAzimuth - loaded.sunAzimuth,
        0,
      );
      this.hdriActive = true;
      this.hdriName = name;
    });
  }

  private load(name: string): Promise<LoadedHdri | null> {
    const cached = this.hdri.get(name);
    if (cached) return cached;

    const base = (import.meta as unknown as { env?: { BASE_URL?: string } }).env?.BASE_URL ?? '/';
    const url = `${base}assets/hdri/${name}/${name}.hdr`;

    const job = new Promise<LoadedHdri | null>((resolve) => {
      const loader = new RGBELoader();
      // Full float, not half. The sun direction is found by scanning the
      // texels, and `Uint16Array` half-floats would have to be decoded by hand
      // to do it. The array is discarded immediately after filtering.
      loader.setDataType(THREE.FloatType);
      loader.load(
        url,
        (tex: THREE.DataTexture) => {
          try {
            tex.mapping = THREE.EquirectangularReflectionMapping;
            const sunAzimuth = brightestAzimuth(tex);
            const target = this.pmrem.fromEquirectangular(tex);
            tex.dispose();
            resolve({ target, sunAzimuth });
          } catch {
            resolve(null);
          }
        },
        undefined,
        // The asset directory is gitignored and optional. A 404 is a normal
        // state of this program, not an error, and it must not reach the
        // console as one or every clean clone looks broken.
        () => resolve(null),
      );
    });

    this.hdri.set(name, job);
    return job;
  }

  dispose(): void {
    this.target?.dispose();
    this.target = null;
    for (const job of this.hdri.values()) {
      void job.then((l) => l?.target.dispose());
    }
    this.hdri.clear();
    this.pmrem.dispose();
  }
}
